services:
  app:
    build: .
    container_name: sdms-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Use Atlas instead of local Mongo
      - MONGODB_URI=mongodb+srv://hy700793:DeviceManagement@cluster0.hilbffv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=your_super_secret_jwt_key_here
      - JWT_EXPIRES_IN=7d
      - DEVICE_INACTIVE_THRESHOLD_HOURS=24
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX_REQUESTS=100
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
